 version: '2'
 services:
   csvserver:
     image: iammrchetan/csvserver:latest
     ports:
       - "9393:9300"
     volumes:
       - "./inputFile:/csvserver/inputdata"
     environment:
       - CSVSERVER_BORDER=Orange
